[package]
name = "tiny_http"
version = "0.0.1"
authors = ["pierre.krieger1708@gmail.com", "coreyf@rwell.org"]

[dependencies]
chunked_transfer = "0.3"
encoding = "0.2"
rustc-serialize = "0.3"
url = "0.2"
